<?php require('template/header.phtml') ?>

<h3>Welcome to Greater Manchester Cars!</h3>

<h3><i>An easier way to find cars in our county</i></h3>
<p>This is the only site you need if you require a new car, wish to sell your own car and live in the Greater Manchester area.</p>
<p><u>Do I live in the right area?</u></p>
<p>Well a simple Google search will tell you that!</p>
<p><u>What kind of cars are available?</u></p>
<p>Hatchbacks, saloons, coupes and convertibles.</p>
<p><u>Why choose us over Auto Trader?</u></p>
<p>Auto Trader is a site run by car sales companies who are only out to make a profit. Our aim with this site is to simply allow individuals to buy and sell cars privately.</p>

<?php require('template/footer.phtml') ?>
