<?php require('template/header.phtml') ?>

<h3>Search</h3>

<input type="text" name='searchBar' onkeypress="handle(event)" placeholder="Search.." id="searchBar">
<script>
    function handle(e){
        if(e.keyCode===13){ //if the enter key is pressed
            e.preventDefault();
            window.location.href = 'browse.php?searchTerm='+document.getElementById('searchBar').value;
        }
    }
</script>
<?php require('template/footer.phtml') ?>
