<?php require('template/header.phtml') ?>

<form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
    <br>
    <table class="table table-hover">
       <thead>
        <tr><th>Student ID</th><th>First name</th><th>Last name</th><th>International</th><th>CourseID</th></tr>

       
       </thead>   
    <tbody> 
        <?php foreach ($view->studentsDataSet as $studentData) {
              echo '<tr> <td>' . $studentData->getStudentID() . '</td> <td>' . $studentData->getFirstName() . '</td> <td>' . $studentData->getLastName() . '</td> <td>' . $studentData->getInternational() .'</td> <td>' . $studentData->getCourseID() . '</td> </td></tr>';
        } ?>
    </tbody>
  </table>  
</form>

<?php require('template/footer.phtml') ?>
